# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
alembic                   1.0.8                      py_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.7.1                 py37_1001    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     1.0.4                 py37_1000    conda-forge
box2d-py                  2.3.8                    pypi_0    pypi
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.2           py37hf0e25f4_1    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                    pypi_0    pypi
conda                     4.6.8                    py37_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
configurable-http-proxy   1.3.0                         0    conda-forge
cryptography              2.6.1            py37h9d9f1b6_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.6           py37hf484d3e_0    conda-forge
cytoolz                   0.9.0.1         py37h14c3975_1001    conda-forge
dask                      1.1.4                      py_0    conda-forge
dask-core                 1.1.4                      py_0    conda-forge
dbus                      1.13.2               h714fa37_1    defaults
decorator                 4.3.2                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
dill                      0.2.9                    py37_0    conda-forge
distributed               1.26.0                   py37_1    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fastcache                 1.0.2           py37h14c3975_1001    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
future                    0.17.1                   pypi_0    pypi
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.0.8           py37hb20f59a_1002    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
gym                       0.14.0                   pypi_0    pypi
h5py                      2.9.0           nompi_py37hf008753_1102    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.5.0                    py37_0    conda-forge
ipykernel                 5.1.0           py37h24bf2e0_1002    conda-forge
ipython                   7.3.0            py37h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jdc                       0.0.9                    pypi_0    pypi
jedi                      0.13.3                   py37_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterhub                0.9.4                 py37_1000    conda-forge
jupyterlab                0.35.4                   py37_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
kiwisolver                1.0.1           py37h6bb024c_1002    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libcurl                   7.64.0               h541490c_2    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libiconv                  1.15              h516909a_1005    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libprotobuf               3.7.0                h8b12597_2    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.0             h90d6eec_1004    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
llvmlite                  0.27.1           py37hdbcaa40_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
mako                      1.0.7                      py_1    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
matplotlib                3.0.3                    py37_0    conda-forge
matplotlib-base           3.0.3            py37h167e16e_0    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
mpc                       1.1.0             hb20f59a_1006    conda-forge
mpfr                      4.0.1             ha14ba45_1000    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
nbconvert                 5.4.1                      py_2    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
nodejs                    11.11.0              hf484d3e_0    conda-forge
notebook                  5.7.5                    py37_0    conda-forge
numba                     0.42.1           py37hf484d3e_0    conda-forge
numexpr                   2.6.9           py37h637b7d7_1000    conda-forge
numpy                     1.15.4          py37_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
packaging                 19.0                       py_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pandas                    0.24.2           py37hf484d3e_0    conda-forge
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.4                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he6710b0_0    defaults
pexpect                   4.6.0                 py37_1000    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    5.4.1           py37h00a061d_1000    conda-forge
pip                       19.2.3                   pypi_0    pypi
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.7.0            py37he1b5a44_1    conda-forge
psutil                    5.6.1            py37h14c3975_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
pycosat                   0.6.3           py37h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pycurl                    7.43.0.2         py37h1ba5d50_0    defaults
pyglet                    1.3.2                    pypi_0    pypi
pygments                  2.3.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyrsistent                0.14.11          py37h14c3975_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.1             h381d211_1003    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python-oauth2             1.1.0            py37h28b3542_1    defaults
pytz                      2018.9                     py_0    conda-forge
pywavelets                1.0.2            py37h3010b51_0    conda-forge
pyyaml                    5.1              py37h14c3975_0    conda-forge
pyzmq                     18.0.1           py37h0e1adb2_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
scikit-image              0.14.2           py37hf484d3e_1    conda-forge
scikit-learn              0.20.3          py37_blas_openblashebff5e3_0  [blas_openblas]  conda-forge
scipy                     1.2.1           py37_blas_openblash1522bff_0  [blas_openblas]  conda-forge
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.8                      py37_0    conda-forge
sqlalchemy                1.3.1            py37h14c3975_0    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
statsmodels               0.9.0           py37h3010b51_1000    conda-forge
sympy                     1.3                   py37_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                 py37_1001    conda-forge
testpath                  0.4.2                 py37_1000    conda-forge
tini                      0.18.0            h14c3975_1001    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.1            py37h14c3975_0    conda-forge
tqdm                      4.36.1                   pypi_0    pypi
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zict                      0.1.4                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
